#!/bin/bash

# Function to display information for a subdomain
display_info() {
    local sub_domain=$1
    local record_type=$(dig +short $sub_domain | awk '{print $4}')
    local destination=$(dig +short $sub_domain)

    echo "The subdomain $sub_domain is a $record_type record and points to $destination"
}

# Main script logic
if [ $# -lt 1 ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

domain=$1
subdomain=${2:-"www lb-01 web-01 web-02"}

if [ -n "$subdomain" ]; then
    display_info $subdomain
else
    for sub in $subdomain; do
        display_info $sub
    done
fi
