#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

apt-get install -y software-properties-common
add-apt-respository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web-01 and web02
echo "
    listen load_balancer
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 137724-web-01 54.236.46.198:80 check
    server 137724-web-02 52.91.123.123:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
