#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd

while IFS=":" read -r username groupid user_info home_directory command;
do
	user_info_split=("${user_info//,/ }")
	password="${user_info_split[0]}"
	user_description=("${user_info_split[@]:1}")

	user_description_string=$(IFS=", "; echo "${user_description[*]}")
	
	echo "The user $username is part of the $groupid gang, lives in $home_directory and rides $command."
	echo "User ID's place is protected by the passcode $password, more info about the user here: $user_description_string"
	echo
done < /etc/passwd
