#!/usr/bin/env bash
# The content of the current directory

for item  in *;
do
	if [[ -e $item && $item != .* ]];
	then
		if [[ -f "$item" && $item == *-* ]];
		then
			part_after=$(echo "$item" | cut -d'-' -f2-)
			echo "$part_after"
		elif [[ -d "$item" ]];
		then
			echo "$item"
		fi
	fi
done
