#!/usr/bin/env bash
# The content of the current directory

for file in *;
do
	if [[ -f $file && $file != .* && $file == *-* ]];
	then
		part_after=$(echo "$file" | cut -d'-' -f2-)
		echo "$part_after"
	fi
done
