#!/usr/bin/env bash
# Backup the hosts file
# Change facebook.com to 8.8.8.8

hosts_backup="/etc/hosts.backup"
cp /etc/hosts "$hosts_backup"
sed -i 's/localhost$/127.0.0.2\n8.8.8.8\tfacebook.com/' "$hosts_backup"
cp -f "$hosts_backup" /etc/hosts
