#!/usr/bin/env bash

# Define the key file names
private_key="school"
public_key="${private_key}.pub"

# Generate the RSA key pair with a passphrase
ssh-keygen -t rsa -b 4096 -f "$private_key" -N "betty"

echo "RSA key pair generated:"
echo "Private key: $private_key"
echo "Public key: $public_key"

